### ISSUE TITLE
Update org.springframework.cloud:spring-cloud-build version to 1.2.1.RELEASE

### ISSUE THREAD

**Issue by trisberg** [spring-cloud-stream-app-starters/core#1]
I think we should update `org.springframework.cloud:spring-cloud-build` version to 1.2.1.RELEASE

**Comment by sobychacko** [comment]
When upgraded to 1.2.1, both hdfs and gemfire app starters have failed due to test failures. We need to investigate why.

**Comment by artembilan** [comment]
This has been fixed via: https://github.com/spring-cloud-stream-app-starters/core/commit/ebabddcf9c5d3e19b648bba335f5079305d67a28

Anything else to do here?

**Comment by sobychacko** [comment]
@artembilan closing the issue.
