### ISSUE TITLE
TriggerConfiguration improper comparison around setting max messages per poll

### ISSUE THREAD

**Issue by loesak** [spring-cloud-stream-app-starters/core#20]
The `PollerMetadata defaultPoller` bean created in `org.springframework.cloud.stream.app.trigger.TriggerConfiguration` has an issue around properly setting the max messages per poll. The code is comparing `this.triggerProperties.getMaxMessages() > -1` but I believe it should be `this.triggerProperties.getMaxMessages() >= -1`. Allowing the max messages per poll to be set to `-1` is a necessity for when a polling operation fetches multiple events and queues them up for retrieval allowing them all to be obtained without waiting for the polling period between each message.

As documented in Spring Integration:

> Note there is no max-messages-per-poll specified. As you’ll learn later the identical poller configuration in the PollingConsumer (e.g., service-activator, filter, router etc.) would have a default value of -1 for max-messages-per-poll which means "execute poling task non-stop unless polling method returns null (e.g., no more Messages in the QueueChannel)" and then sleep for 1 second.
> However in the SourcePollingChannelAdapter it is a bit different. The default value for max-messages-per-poll will be set to 1 by default unless you explicitly set it to a negative value (e.g., -1). It is done so to make sure that poller can react to a LifeCycle events (e.g., start/stop) and prevent it from potentially spinning in the infinite loop if the implementation of the custom method of the MessageSource has a potential to never return null and happened to be non-interruptible.
> However if you are sure that your method can return null and you need the behavior where you want to poll for as many sources as available per each poll, then you should explicitly set max-messages-per-poll to a negative value.

http://docs.spring.io/spring-integration/docs/4.3.10.RELEASE/reference/html/messaging-channels-section.html#channel-adapter-namespace-inbound

**Comment by artembilan** [comment]
Well, actually in the target logic it doesn't matter:
```
while (AbstractPollingEndpoint.this.initialized
						&& (AbstractPollingEndpoint.this.maxMessagesPerPoll <= 0
						|| count < AbstractPollingEndpoint.this.maxMessagesPerPoll)) {
```
So, semantically a `0` really means *unbounded* as well.

And default value in Spring Integration is:
```
public static final int MAX_MESSAGES_UNBOUNDED = Integer.MIN_VALUE;
```
Which isn't `-1` anyway.

But I see your point regarding the code:
```
pollerMetadata.setMaxMessagesPerPoll(
               this.triggerProperties.getMaxMessages() > -1L
                                  ? this.triggerProperties.getMaxMessages()
                                  : 1L);
```
So, when we really use `TriggerPropertiesMaxMessagesDefaultUnlimited` with its `private long maxMessages = -1L;` we really don't get a gain and end-up with the same `1` when we would like to have unlimited amount of messages per one poll.

So, jumping to your PR for review 😄

**Comment by loesak** [comment]
I guess that I was never aware that a setting of `0` would be equivalent to a setting of `-1`. I guess from reading the documentation that the use of `-1` stuck with me as the desired value for unbounded.
