### ISSUE TITLE
Move ContentTypeEnvironmentPostProcessor to core

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud-stream-app-starters/core#24]
Move https://github.com/spring-cloud-stream-app-starters/load-generator/blob/master/spring-cloud-starter-stream-source-load-generator/src/main/java/org/springframework/cloud/stream/app/load/generator/source/ContentTypeEnvironmentPostProcessor.java so it can be shared across other app projects needing the same functionality

**Comment by chrisjs** [comment]
@artembilan @sobychacko so i figured this would have been fairly straightforward - possibly by registering the `EnvironmentPostProcessor` programmatically and setting the appropriate values, but unfortunately from what I can tell, its loaded a bit too early to have the ability to do so (set params via constructor etc) and needs to be registered through `spring.factories`. seems it would be the same with say an `ApplicationListener` after an environment prepared event occurs.

so.. i think that leaves things at:

1 - close this issue and make an `EnvironmentPostProcessor` in each project where needed. seems there will likely be a bit of duplication going around with this approach.

2 - create a property in the application yml, say for example `contentTypeOverride`. if the user hasn't already set one (overriding the default JSON type), use the `contentTypeOverride` value. this approach let you re-use a common `EnvironmentPostProcessor` class with the downfall of having to make config files with "override" values and so on in them.

while id rather not duplicate things all over, unless you have another thought on how this may be accomplished option 1 would seem better than option 2.

thoughts?

**Comment by artembilan** [comment]
We had similar discussion yesterday with @tzolov when he would like to fix TCP source for SCSt 2.0 compatibility. So far we just decided to copy/paste your class there as is. The middle ground for more general solution we came is like this:

1. Have such a class exactly here in `core` to be available for any App Starters with the `octet-stream` by default.
2. When we need such an override we just add in that project `spring.factories` with an appropriate entry to this class.
3. If we need some different `content-type` by default, we only should extend this class and provide that content-type via super ctor on the compile level.

Does it make sense?

We have a call in 20 mins about this project - feel free to join and discuss this meter there as well.

Thank you for your cool contribution!

**Comment by chrisjs** [comment]
"move" also implies patching up `load-generator` to use this

**Comment by chrisjs** [comment]
pr @ https://github.com/spring-cloud-stream-app-starters/core/pull/25 

ive modified it a bit from its original state to support overriding defaults. after this gets merged ill push the mods for `load-generator` and `scriptable-transform`

**Comment by chrisjs** [comment]
PR for `load-generator` is at https://github.com/spring-cloud-stream-app-starters/load-generator/pull/4 which should close this issue out.
