### ISSUE TITLE
Declarative Micrometer Tags enhancement functionality for all app starters

### ISSUE THREAD

**Issue by tzolov** [spring-cloud-stream-app-starters/core#70]
Adding a declarative Micrometer Tags injection utilities, common for all app starters. 

The idea is to provide the same fixed/expression based tags enhancement functionality available in the [Counter](https://github.com/spring-cloud-stream-app-starters/analytics) to all app starters. 

For example,  any app starter should be able to register additional Micrometer tags, with values dynamically resolved from the Message objects using SpEL expressions:
```
analytics.tag.expression.author=#jsonPath(payload,'$..author')
```

**Comment by sabbyanandan** [comment]
This is not applicable anymore.
